const categories = {
  Part1NGSL: [
   { "question": "Act", "answer": "Bertindak" },
{ "question": "Action", "answer": "Beraksi" },
{ "question": "Activity", "answer": "Aktivitas" },
{ "question": "Actually", "answer": "Sebenernya" },
{ "question": "Add", "answer": "Menambah" },
{ "question": "Address", "answer": "Alamat" },
{ "question": "Administration", "answer": "Pendaftaran" },
{ "question": "Admit", "answer": "Mengakui" },
{ "question": "Adult", "answer": "Dewasa" },
{ "question": "a", "answer": "Sebuah" },
{ "question": "Ability", "answer": "Kemampuan" },
{ "question": "Able", "answer": "Mampu" },
{ "question": "About", "answer": "Tentang" },
{ "question": "Above", "answer": "Diatas" },
{ "question": "Accept", "answer": "Menerima" },
{ "question": "According", "answer": "Menurut" },
{ "question": "Account", "answer": "Akun" },
{ "question": "Ago", "answer": "Yang lalu" },
{ "question": "Agree", "answer": "Setuju" },
{ "question": "Agreement", "answer": "Persetujuan" },
{ "question": "Ahead", "answer": "Didepan" },
{ "question": "Air", "answer": "Udara" },
{ "question": "All", "answer": "Semua" },
{ "question": "Allow", "answer": "Memperbolehkan" },
{ "question": "Almost", "answer": "Hampir" },
{ "question": "Alone", "answer": "Sendirian" },
{ "question": "Along", "answer": "Sepanjang" },
{ "question": "Already", "answer": "Sudah" },
{ "question": "Also", "answer": "Juga" },
{ "question": "Although", "answer": "Walaupun" },
{ "question": "Across", "answer": "Menyebrang" },
{ "question": "Affect", "answer": "Mempengaruhi" },
{ "question": "After", "answer": "Setelah" },
{ "question": "Again", "answer": "Lagi" },
{ "question": "Genius", "answer": "Jenius" },
{ "question": "Age", "answer": "Usia / masa" },
{ "question": "Girl", "answer": "Gadis" },
{ "question": "Group", "answer": "Kelompok" },
{ "question": "Another", "answer": "Yang lain" },
{ "question": "Answer", "answer": "Jawaban" },
{ "question": "Any", "answer": "Ada" },
{ "question": "Anyone", "answer": "Siapapun" },
{ "question": "Anything", "answer": "Apasaja" },
{ "question": "Anytime", "answer": "Kapanpun" },
{ "question": "Apply", "answer": "Menerapkan" },
{ "question": "Apple", "answer": "Apel" },
{ "question": "Area", "answer": "Lokasi" },
{ "question": "Argue", "answer": "Membantah" },
{ "question": "Arm", "answer": "Lengan" },
{ "question": "Always", "answer": "Selalu" },
{ "question": "American", "answer": "Warga amerika" },
{ "question": "Among", "answer": "Diantara" },
{ "question": "Amount", "answer": "Jumlah" },
{ "question": "Animal", "answer": "Hewan" },
{ "question": "And", "answer": "Dan" },
{ "question": "Anymore", "answer": "Lagi" },
{ "question": "At all", "answer": "Selalu" },
{ "question": "Attack", "answer": "Menyerang" },
{ "question": "Attention", "answer": "Perhatian" },
{ "question": "At a time", "answer": "Sekaligus" },
{ "question": "Audience", "answer": "Penonton / pendengar" },
{ "question": "Author", "answer": "Pengarang" },
{ "question": "Authority", "answer": "Wewenang" },
{ "question": "Available", "answer": "Tersedia" },
{ "question": "Avoid", "answer": "Menghindari" },
{ "question": "Away", "answer": "Jauh" },
{ "question": "Around", "answer": "Disekitar" },
{ "question": "Arrive", "answer": "Tiba" },
{ "question": "Art", "answer": "Seni" },
{ "question": "Article", "answer": "Artikel / tulisan" },
{ "question": "Artist", "answer": "Artis" },
{ "question": "As", "answer": "Sebagai" },
{ "question": "Ask", "answer": "Bertanya" },
{ "question": "As follows", "answer": "Sebagai berikut" },
{ "question": "Beautiful", "answer": "Cantik / indah" },
{ "question": "Because", "answer": "Karena" },
{ "question": "Become", "answer": "Menjadi" },
{ "question": "Bed", "answer": "Ranjang tidur" },
{ "question": "Before", "answer": "Sebelum" },
{ "question": "Begin", "answer": "Mulai" },
{ "question": "Behavior", "answer": "Tingkah laku" },
{ "question": "Behind", "answer": "Dibelakang" },
{ "question": "Believe", "answer": "Memercayai" },
{ "question": "Benefit", "answer": "Manfaat" },
{ "question": "Baby", "answer": "Bayi / sayang" },
{ "question": "Back", "answer": "Kembali" },
{ "question": "Bad", "answer": "Buruk" },
{ "question": "Bag", "answer": "Tas" },
{ "question": "Ball", "answer": "Bola" },
{ "question": "Bank", "answer": "Bank" },
{ "question": "Be all ears", "answer": "Mendengar dengan baik" },
{ "question": "Bath", "answer": "Mandi" },
{ "question": "Bother", "answer": "Mengganggu" },
{ "question": "Between", "answer": "Diantara" },
{ "question": "Best", "answer": "Terbaik" },
{ "question": "Better", "answer": "Lebih baik" },
{ "question": "Boy", "answer": "Anak laki laki" },
{ "question": "Break", "answer": "Istirahat / merusak / menghancurkan" },
{ "question": "Bring", "answer": "Membawa" },
{ "question": "Both", "answer": "Keduanya" },
    ],
  Part2NGSL: [
   { "question": "Budget", "answer": "Anggaran" },
{ "question": "Building", "answer": "Bangunan" },
{ "question": "Buy", "answer": "Membeli" },
{ "question": "Butterfly", "answer": "Kupu - kupu" },
{ "question": "But", "answer": "Tetapi" },
{ "question": "Bet", "answer": "Bertaruh" },
{ "question": "Beyond", "answer": "Melebihi" },
{ "question": "Big", "answer": "Besar" },
{ "question": "Beach", "answer": "Pantai" },
{ "question": "Bike", "answer": "Spede" },
{ "question": "Bit", "answer": "Sedikit" },
{ "question": "Black", "answer": "Hitam" },
{ "question": "Blood", "answer": "Darah" },
{ "question": "Blue", "answer": "Biru" },
{ "question": "Button up", "answer": "Mengancing" },
{ "question": "Body", "answer": "Tubuh" },
{ "question": "Box", "answer": "Kotak" },
{ "question": "Bottom", "answer": "Bawah" },
{ "question": "By", "answer": "Oleh / dengan" },
{ "question": "Bridge", "answer": "Jembatan" },
{ "question": "Car", "answer": "Mobil" },
{ "question": "Call", "answer": "Menelpon" },
{ "question": "Can", "answer": "Dapat" },
{ "question": "Care", "answer": "Peduli" },
{ "question": "Career", "answer": "Karir" },
{ "question": "Change", "answer": "Perubahan" },
{ "question": "Chance", "answer": "Kesempatan" },
{ "question": "Course", "answer": "Kursus" },
{ "question": "City", "answer": "Kota" },
{ "question": "Cake", "answer": "Kue" },
{ "question": "Choice", "answer": "Pilihan" },
{ "question": "Close", "answer": "Menutup" },
{ "question": "Cry", "answer": "Menangis" },
{ "question": "Cut", "answer": "Memotong" },
{ "question": "Cool", "answer": "Keren" },
{ "question": "Confident", "answer": "Percaya diri" },
{ "question": "Coach", "answer": "Pelatih" },
{ "question": "Clean", "answer": "Membersihkan" },
{ "question": "Choose", "answer": "Memilih" },
{ "question": "Clothes", "answer": "Pakaian" },
{ "question": "Challenge", "answer": "Tantangan" },
{ "question": "Calm", "answer": "Tenang" },
{ "question": "Carry", "answer": "Membawa" },
{ "question": "Chat", "answer": "Mengobrol" },
{ "question": "Class", "answer": "Kelas" },
{ "question": "Clear", "answer": "Bersih / jelas" },
{ "question": "Classmate", "answer": "Teman sekelas" },
{ "question": "Color", "answer": "Warna" },
{ "question": "Coconut", "answer": "Kelapa" },
{ "question": "Cold", "answer": "Dingin" },
{ "question": "Center", "answer": "Pusat" },
{ "question": "Comment", "answer": "Komentar" },
{ "question": "Common", "answer": "Umum / biasa" },
{ "question": "Certain", "answer": "Tentu" },
{ "question": "Certainly", "answer": "Pasti" },
{ "question": "Chair", "answer": "Kursi" },
{ "question": "Cook", "answer": "Memasak" },
{ "question": "Country", "answer": "Negara" },
{ "question": "Corner", "answer": "Sudut" },
{ "question": "Consider", "answer": "Mempertimbangkan" },
{ "question": "Cost", "answer": "Harga" },
{ "question": "Couple", "answer": "Pasangan" },
{ "question": "Continue", "answer": "Terus" },
{ "question": "Boil", "answer": "Merebus" },
{ "question": "Bowl", "answer": "Mangkok" },
{ "question": "Breath", "answer": "Bernafas" },
{ "question": "Brush", "answer": "Menyikat" },
{ "question": "Character", "answer": "Karakter" },
{ "question": "Check", "answer": "Memeriksa" },
{ "question": "Create", "answer": "Membuat" },
{ "question": "Crime", "answer": "Kejahatan" },
{ "question": "Company", "answer": "Perusahaan" },
{ "question": "Compare", "answer": "Membandingkan" },
{ "question": "Computer", "answer": "Komputer" },
{ "question": "Condition", "answer": "Kondisi" },
{ "question": "Decade", "answer": "Dekade" },
{ "question": "Delivery", "answer": "Pengiriman" },
{ "question": "Diamond", "answer": "Berlian" },
{ "question": "Dance", "answer": "Menari" },
{ "question": "Dear", "answer": "Sayang" },
{ "question": "Deer", "answer": "Rusa" },
{ "question": "Danger", "answer": "Bahaya" },
{ "question": "Daughter", "answer": "Anak perempuan" },
{ "question": "Date", "answer": "Tanggal / kurma" },
{ "question": "Dady", "answer": "Ayah" },
{ "question": "Dead", "answer": "Mati" },
{ "question": "Dark", "answer": "Gelap" },
{ "question": "Devil", "answer": "Iblis" },
{ "question": "Diary", "answer": "Buku harian" },
{ "question": "Die", "answer": "Meninggal" },
{ "question": "Dictionary", "answer": "Kamus" },
{ "question": "Diet", "answer": "Diet" },
{ "question": "Day", "answer": "Hari" },
{ "question": "Difference", "answer": "Perbedaan" },
{ "question": "Dinner", "answer": "Makan malam" },
{ "question": "Deep", "answer": "Dalam" },
{ "question": "Dirty", "answer": "Kotor" },
{ "question": "Dishes", "answer": "Piring" },
{ "question": "Deal", "answer": "Sepakat" },
{ "question": "Decide", "answer": "Memutuskan" },
    ],
  Part3NGSL: [
   { "question": "Decision", "answer": "Keputusan" },
{ "question": "Difficult", "answer": "Sulit" },
{ "question": "Different", "answer": "Berbeda" },
{ "question": "Do", "answer": "Melakukan" },
{ "question": "Doctor", "answer": "Dokter" },
{ "question": "Dog", "answer": "Anjing" },
{ "question": "Door", "answer": "Pintu" },
{ "question": "Document", "answer": "Dokumen" },
{ "question": "Doll", "answer": "Boneka" },
{ "question": "Detail", "answer": "Detail" },
{ "question": "Dolphin", "answer": "Lumba - lumba" },
{ "question": "Donation", "answer": "Sumbangan" },
{ "question": "Donkey", "answer": "Keledai" },
{ "question": "Double", "answer": "Dobel" },
{ "question": "Down", "answer": "Turun" },
{ "question": "Dream", "answer": "Mimpi" },
{ "question": "Dragon", "answer": "Naga" },
{ "question": "Diaper", "answer": "Popok" },
{ "question": "Drink", "answer": "Minum" },
{ "question": "Drawer", "answer": "Laci" },
{ "question": "Drive", "answer": "Mengendara" },
{ "question": "Driver", "answer": "Pengendara" },
{ "question": "Dive", "answer": "Menyelam" },
{ "question": "Dizzy", "answer": "Pusing" },
{ "question": "Dryer", "answer": "Pengering" },
{ "question": "Duet", "answer": "Duet" },
{ "question": "Duty", "answer": "Tugas" },
{ "question": "Drop", "answer": "Penurunan" },
{ "question": "Deffense", "answer": "Pertahanan" },
{ "question": "Degree", "answer": "Tingkat" },
{ "question": "Eagle", "answer": "Elang" },
{ "question": "Ear", "answer": "Telinga" },
{ "question": "Describe", "answer": "Menggambarkan" },
{ "question": "Design", "answer": "Rancangan" },
{ "question": "Early", "answer": "Dini / awal" },
{ "question": "Earth", "answer": "Bumi" },
{ "question": "Direction", "answer": "Arah" },
{ "question": "Earthquake", "answer": "Gempa bumi" },
{ "question": "Edge", "answer": "Tepi" },
{ "question": "Easy", "answer": "Mudah" },
{ "question": "Eat", "answer": "Makan" },
{ "question": "Effort", "answer": "Upaya" },
{ "question": "Eight", "answer": "Delapan" },
{ "question": "Either", "answer": "Antar / salah satu" },
{ "question": "Each", "answer": "Setiap" },
{ "question": "Else", "answer": "Yang lain" },
{ "question": "Even", "answer": "Bahkan" },
{ "question": "Eclipse", "answer": "Gerhana" },
{ "question": "Discuss", "answer": "Diskusi" },
{ "question": "Every", "answer": "Setiap" },
{ "question": "End", "answer": "Akhir" },
{ "question": "Employee", "answer": "Pegawai" },
{ "question": "Egg", "answer": "Telur" },
{ "question": "Ego", "answer": "Egois" },
{ "question": "Elbow", "answer": "Siku" },
{ "question": "East", "answer": "Timur" },
{ "question": "Emergency", "answer": "Darurat" },
{ "question": "Enemy", "answer": "Musuh" },
{ "question": "During", "answer": "Selama" },
{ "question": "Economy", "answer": "Ekonomi" },
{ "question": "Energy", "answer": "Energi" },
{ "question": "Engineer", "answer": "Insinyur" },
{ "question": "Especially", "answer": "Terutama" },
{ "question": "Epic", "answer": "Epik" },
{ "question": "Eleven", "answer": "Sebelas" },
{ "question": "Elephant", "answer": "Gajah" },
{ "question": "Event", "answer": "Kejadian / acara" },
{ "question": "Ever", "answer": "Pernah" },
{ "question": "Everything", "answer": "Semuanya" },
{ "question": "Everybody", "answer": "Setiap orang" },
{ "question": "Everyone", "answer": "Siapapun" },
{ "question": "Evening", "answer": "Petang" },
{ "question": "Evidence", "answer": "Bukti" },
{ "question": "Enjoy", "answer": "Menikmati" },
{ "question": "Enough", "answer": "Cukup" },
{ "question": "Enter", "answer": "Memasukan" },
{ "question": "Entire", "answer": "Seluruh" },
{ "question": "Equal", "answer": "Sama" },
{ "question": "Exactly", "answer": "Persis" },
{ "question": "Example", "answer": "Contoh" },
{ "question": "Eraser", "answer": "Penghapus" },
{ "question": "Exist", "answer": "Ada" },
{ "question": "Error", "answer": "Kesalahan" },
{ "question": "Experience", "answer": "Pengalaman" },
{ "question": "Expert", "answer": "Ahli" },
{ "question": "Explain", "answer": "Menjelaskan" },
{ "question": "Eye", "answer": "Mata" },
{ "question": "Escape", "answer": "Melarikan diri" },
{ "question": "Everywhere", "answer": "Dimanapun" },
{ "question": "Evolution", "answer": "Evolusi" },
{ "question": "Face", "answer": "Wajah" },
{ "question": "Factor", "answer": "Faktor" },
{ "question": "Far", "answer": "Jauh" },
{ "question": "Fail", "answer": "Gagal" },
{ "question": "Father", "answer": "Ayah" },
{ "question": "Fear", "answer": "Takut" },
{ "question": "Fall", "answer": "Jatuh" },
{ "question": "Feel", "answer": "Merasa" },
{ "question": "Afraid", "answer": "Takut" },
{ "question": "Fate", "answer": "Takdir" },
    ],
  Part4NGSL: [
   { "question": "Feeling", "answer": "Perasaan" },
{ "question": "Few", "answer": "Beberapa" },
{ "question": "Field", "answer": "Bidang / ladang" },
{ "question": "Fire", "answer": "Api" },
{ "question": "Family", "answer": "Keluarga" },
{ "question": "First", "answer": "Pertama" },
{ "question": "Fish", "answer": "Ikan" },
{ "question": "Five", "answer": "Lima" },
{ "question": "Floor", "answer": "Lantai" },
{ "question": "Fly", "answer": "Terbang" },
{ "question": "Focus", "answer": "Fokus" },
{ "question": "Follow", "answer": "Mengikuti" },
{ "question": "Food", "answer": "Makanan" },
{ "question": "Foot", "answer": "Kaki" },
{ "question": "For", "answer": "Untuk" },
{ "question": "Force", "answer": "Memaksa" },
{ "question": "Farmer", "answer": "Petani" },
{ "question": "From", "answer": "Dari" },
{ "question": "Fast", "answer": "Cepat" },
{ "question": "Full", "answer": "Penuh" },
{ "question": "Favorite", "answer": "Favorit" },
{ "question": "Future", "answer": "Masa depan" },
{ "question": "Fishing", "answer": "Memancing" },
{ "question": "Fly", "answer": "Terbang" },
{ "question": "Fruit", "answer": "Buah" },
{ "question": "Freedom", "answer": "Kebebasan / merdeka" },
{ "question": "Figure out", "answer": "Mencari tau" },
{ "question": "Fill", "answer": "Mengisi" },
{ "question": "Friend", "answer": "Teman" },
{ "question": "Final", "answer": "Terakhir" },
{ "question": "Finally", "answer": "Akhirnya" },
{ "question": "Frog", "answer": "Katak" },
{ "question": "Find", "answer": "Temukan / menemukan" },
{ "question": "Fine", "answer": "Baik" },
{ "question": "Finger", "answer": "Jari" },
{ "question": "Finish", "answer": "Selesai" },
{ "question": "Fun", "answer": "Menyenangkan" },
{ "question": "Forget", "answer": "Lupa" },
{ "question": "Four", "answer": "Empat" },
{ "question": "Flower", "answer": "Bunga" },
{ "question": "Flour", "answer": "Tepung" },
{ "question": "Forest", "answer": "Hutan" },
{ "question": "Fold", "answer": "Melipat" },
{ "question": "Fool", "answer": "Menipu / bodoh / membodoh bodohi" },
{ "question": "Fork", "answer": "Garpu" },
{ "question": "General", "answer": "Umum" },
{ "question": "Gate", "answer": "Gerbang" },
{ "question": "Go", "answer": "Pergi" },
{ "question": "Good", "answer": "Bagus" },
{ "question": "Gift", "answer": "Hadiah / pemberian" },
{ "question": "Great", "answer": "Bagus" },
{ "question": "Green", "answer": "Hijau" },
{ "question": "Ground", "answer": "Tanah" },
{ "question": "Goal", "answer": "Tujuan" },
{ "question": "Gold", "answer": "Emas" },
{ "question": "Government", "answer": "Pemerintah" },
{ "question": "Free", "answer": "Gratis" },
{ "question": "Grow", "answer": "Tumbuh" },
{ "question": "Guide", "answer": "Panduan" },
{ "question": "Habit", "answer": "Kebiasaan" },
{ "question": "Hair", "answer": "Rambut" },
{ "question": "Hand", "answer": "Tangan" },
{ "question": "Happy", "answer": "Senang" },
{ "question": "Hard", "answer": "Keras" },
{ "question": "Handle", "answer": "Menangani" },
{ "question": "Have", "answer": "Mempunyai" },
{ "question": "Hate", "answer": "Benci" },
{ "question": "Health", "answer": "Sehat / Kesehatan" },
{ "question": "Hear", "answer": "Mendengar" },
{ "question": "High", "answer": "Tinggi" },
{ "question": "Hobby", "answer": "Hobi" },
{ "question": "Guess", "answer": "Menebak" },
{ "question": "Hold", "answer": "Memegang / menahan" },
{ "question": "History", "answer": "Sejarah" },
{ "question": "Hair", "answer": "Rambut" },
{ "question": "Home", "answer": "Rumah" },
{ "question": "Holiday", "answer": "Liburan" },
{ "question": "Heavy", "answer": "Berat" },
{ "question": "Help", "answer": "Membantu" },
{ "question": "Hope", "answer": "Berharap" },
{ "question": "Here", "answer": "Disini" },
{ "question": "House", "answer": "Rumah" },
{ "question": "Hour", "answer": "Jam" },
{ "question": "Housework", "answer": "Pekerjaan rumah" },
{ "question": "How", "answer": "Bagaimana" },
{ "question": "However", "answer": "Namun / bagaimanapun" },
{ "question": "Hurt", "answer": "Menyakiti" },
{ "question": "Human", "answer": "Manusia" },
{ "question": "Hundred", "answer": "Ratus" },
{ "question": "Husband", "answer": "Suami" },
{ "question": "I", "answer": "Saya" },
{ "question": "Idea", "answer": "Ide" },
{ "question": "Identify", "answer": "Mengenali / mengidentifikasi" },
{ "question": "ill", "answer": "Sakit" },
{ "question": "If", "answer": "Jika" },
{ "question": "Him", "answer": "Dia (laki - laki)" },
{ "question": "Illustration", "answer": "Ilustrasi" },
{ "question": "Important", "answer": "Penting" },
{ "question": "Income", "answer": "Pendapatan" },
{ "question": "Information", "answer": "Informasi" },
    ],
  Part5NGSL: [
   { "question": "Inside", "answer": "Didalam" },
{ "question": "Iron", "answer": "Besi" },
{ "question": "Island", "answer": "Pulau" },
{ "question": "Hosiptal", "answer": "Rumah sakit" },
{ "question": "Hot", "answer": "Panas" },
{ "question": "Half", "answer": "Setengah" },
{ "question": "Hero", "answer": "Pahlawan" },
{ "question": "Garden", "answer": "Taman" },
{ "question": "Hit", "answer": "Memukul" },
{ "question": "Holiday", "answer": "Hari libur" },
{ "question": "Instead of", "answer": "Daripada" },
{ "question": "Interested", "answer": "Tertarik" },
{ "question": "Image", "answer": "Gambaran" },
{ "question": "Interesting", "answer": "Menarik" },
{ "question": "Internasional", "answer": "Internasional" },
{ "question": "Interview", "answer": "Wawancara" },
{ "question": "Into", "answer": "Ke" },
{ "question": "Immediately", "answer": "Segera" },
{ "question": "Important", "answer": "Penting" },
{ "question": "Issue", "answer": "Isu" },
{ "question": "It", "answer": "Itu" },
{ "question": "It's", "answer": "Adalah" },
{ "question": "Improve", "answer": "Memperbaiki / meningkatkan" },
{ "question": "In", "answer": "Di" },
{ "question": "Include", "answer": "Termasuk" },
{ "question": "Innovation", "answer": "Inovasi" },
{ "question": "Infinity", "answer": "Tak terhingga" },
{ "question": "Indeed", "answer": "Memang" },
{ "question": "Industry", "answer": "Industri" },
{ "question": "Individual", "answer": "Individu" },
{ "question": "Justice", "answer": "Keadilan" },
{ "question": "Item", "answer": "Hal" },
{ "question": "Job", "answer": "Pekerjaan" },
{ "question": "Join", "answer": "Ikut" },
{ "question": "Jogging", "answer": "Joging" },
{ "question": "Juice", "answer": "Jus" },
{ "question": "Late", "answer": "Telat" },
{ "question": "Later", "answer": "Kemudian" },
{ "question": "Laugh", "answer": "Tertawa" },
{ "question": "Law", "answer": "Hukum" },
{ "question": "Lawyer", "answer": "Pengacara" },
{ "question": "Lemon", "answer": "Lemon" },
{ "question": "Leader", "answer": "Pemimpin" },
{ "question": "Legend", "answer": "Legenda" },
{ "question": "Learn", "answer": "Belajar" },
{ "question": "Listen", "answer": "Mendengar" },
{ "question": "Just", "answer": "Hanya" },
{ "question": "Keep", "answer": "Tepat" },
{ "question": "Key", "answer": "Kunci" },
{ "question": "Life", "answer": "Hidup" },
{ "question": "List", "answer": "Daftar" },
{ "question": "Kind", "answer": "Jenis" },
{ "question": "Kitchen", "answer": "Dapur" },
{ "question": "Know", "answer": "Tau" },
{ "question": "Knowledge", "answer": "Pengetahuan" },
{ "question": "Location", "answer": "Lokasi" },
{ "question": "Language", "answer": "Bahasa" },
{ "question": "Large", "answer": "Besar" },
{ "question": "Last", "answer": "Terakhir" },
{ "question": "Leave", "answer": "Meninggalkan" },
{ "question": "Left", "answer": "Kiri" },
{ "question": "Light", "answer": "Cahaya" },
{ "question": "Long", "answer": "Panjang" },
{ "question": "Look", "answer": "Melihat" },
{ "question": "Lose", "answer": "Kalah" },
{ "question": "Lost", "answer": "Tersesat" },
{ "question": "Lot", "answer": "Banyak" },
{ "question": "Love", "answer": "Sayang" },
{ "question": "Low", "answer": "Rendah" },
{ "question": "Letter", "answer": "Surat" },
{ "question": "Level", "answer": "Tingkat" },
{ "question": "Lie", "answer": "Berbohong" },
{ "question": "Lifestyle", "answer": "Gaya hidup" },
{ "question": "Lifetime", "answer": "Masa" },
{ "question": "Like", "answer": "Suka" },
{ "question": "Likely", "answer": "Mungkin" },
{ "question": "Line", "answer": "Garis" },
{ "question": "Logic", "answer": "Logika" },
{ "question": "Lord", "answer": "Tuan" },
{ "question": "Little", "answer": "Sedikit" },
{ "question": "Live", "answer": "Hidup" },
{ "question": "Machine", "answer": "Mesin" },
{ "question": "Magazine", "answer": "Koran" },
{ "question": "Man", "answer": "Lelaki" },
{ "question": "Legal", "answer": "Sah" },
{ "question": "Less", "answer": "Kurang" },
{ "question": "Let", "answer": "Membiarkan" },
{ "question": "Manner", "answer": "Cara" },
{ "question": "Maintain", "answer": "Mempertahankan" },
{ "question": "Major", "answer": "Utama" },
{ "question": "Market", "answer": "Pasar" },
{ "question": "Make", "answer": "Membuat" },
{ "question": "Master", "answer": "Guru" },
{ "question": "Matter", "answer": "Masalah" },
{ "question": "Meals", "answer": "Makanan / cemilan" },
{ "question": "Meat", "answer": "Daging" },
{ "question": "Many", "answer": "Banyak" },
{ "question": "Media", "answer": "Media" },
{ "question": "Marriage", "answer": "Pernikahan" },
{ "question": "Material", "answer": "Bahan" },
    ],
  Part6NGSL: [
   { "question": "Meet", "answer": "Bertemu" },
{ "question": "Meeting", "answer": "Pertemuan" },
{ "question": "Member", "answer": "Anggota" },
{ "question": "Memory", "answer": "Penyimpanan" },
{ "question": "Mention", "answer": "Menyebut" },
{ "question": "Message", "answer": "Pesan" },
{ "question": "Method", "answer": "Metode" },
{ "question": "Middle", "answer": "Tengah" },
{ "question": "Might", "answer": "Mungkin" },
{ "question": "Military", "answer": "Militer" },
{ "question": "Million", "answer": "Juta" },
{ "question": "Mind", "answer": "Pikiran" },
{ "question": "Minute", "answer": "Menit" },
{ "question": "Miss", "answer": "Rindu" },
{ "question": "Mission", "answer": "Misi" },
{ "question": "Model", "answer": "Model" },
{ "question": "Matter", "answer": "Masalah" },
{ "question": "May", "answer": "Mungkin" },
{ "question": "Music", "answer": "Musik" },
{ "question": "Maybe", "answer": "Mungkin" },
{ "question": "Me", "answer": "Saya" },
{ "question": "Mean", "answer": "Berarti" },
{ "question": "Measure", "answer": "Mengukur" },
{ "question": "Mix up", "answer": "Mengacaukan" },
{ "question": "Medical", "answer": "Medis" },
{ "question": "Modern", "answer": "Modern" },
{ "question": "Moment", "answer": "Saat" },
{ "question": "Money", "answer": "Uang" },
{ "question": "Month", "answer": "Bulan" },
{ "question": "More", "answer": "Lebih" },
{ "question": "Morning", "answer": "Pagi" },
{ "question": "Most", "answer": "Paling" },
{ "question": "My", "answer": "Punya saya" },
{ "question": "Myself", "answer": "Diri" },
{ "question": "Name", "answer": "Nama" },
{ "question": "Nation", "answer": "Bangsa" },
{ "question": "National", "answer": "Nasional" },
{ "question": "Natural", "answer": "Alam" },
{ "question": "Nature", "answer": "Alam" },
{ "question": "Near", "answer": "Dekat" },
{ "question": "Nearly", "answer": "Hampir" },
{ "question": "Necessary", "answer": "Perlu" },
{ "question": "Need", "answer": "Butuh" },
{ "question": "Network", "answer": "Jaringan" },
{ "question": "Never", "answer": "Tidak pernah" },
{ "question": "New", "answer": "Baru" },
{ "question": "Mother", "answer": "Ibu" },
{ "question": "Mouth", "answer": "Mulut" },
{ "question": "Move", "answer": "Pindah" },
{ "question": "Movement", "answer": "Gerakan" },
{ "question": "Movie", "answer": "Film" },
{ "question": "Mr", "answer": "Bapak / tuan" },
{ "question": "Mrs", "answer": "Nyonya" },
{ "question": "Much", "answer": "Banyak" },
{ "question": "Music", "answer": "Musik" },
{ "question": "Must", "answer": "Harus" },
{ "question": "News", "answer": "Berita" },
{ "question": "Newspaper", "answer": "Koran" },
{ "question": "Next", "answer": "Lanjut" },
{ "question": "Nice", "answer": "Bagus" },
{ "question": "Night", "answer": "Malam" },
{ "question": "No", "answer": "Tidak" },
{ "question": "None", "answer": "Tidak ada" },
{ "question": "Nor", "answer": "Maupun" },
{ "question": "North", "answer": "Utara" },
{ "question": "Officer", "answer": "Petugas" },
{ "question": "Official", "answer": "Resmi" },
{ "question": "Often", "answer": "Sering" },
{ "question": "Oil", "answer": "Minyak" },
{ "question": "Ok", "answer": "Baik" },
{ "question": "Old", "answer": "Tua" },
{ "question": "On", "answer": "Di" },
{ "question": "Once", "answer": "Sekali" },
{ "question": "One", "answer": "Satu" },
{ "question": "Only", "answer": "Hanya" },
{ "question": "On to", "answer": "Ke" },
{ "question": "Not", "answer": "Tidak" },
{ "question": "Note", "answer": "Catatan" },
{ "question": "Nothing", "answer": "Tidak ada" },
{ "question": "Notice", "answer": "Memperhatikan" },
{ "question": "Now", "answer": "Sekarang" },
{ "question": "No way", "answer": "Tidak sama sekali" },
{ "question": "Number", "answer": "Nomor" },
{ "question": "Occur", "answer": "Terjadi" },
{ "question": "Of", "answer": "Dari" },
{ "question": "Off", "answer": "Mati" },
{ "question": "Offer", "answer": "Menawarkan" },
{ "question": "Office", "answer": "Kantor" },
{ "question": "Open", "answer": "Buka" },
{ "question": "Operation", "answer": "Operasi" },
{ "question": "Opportunity", "answer": "Kesempatan" },
{ "question": "Option", "answer": "Pilihan" },
{ "question": "Or", "answer": "Atau" },
{ "question": "Order", "answer": "Memesan" },
{ "question": "Organization", "answer": "Organisasi" },
{ "question": "Other", "answer": "Lain" },
{ "question": "Otherwise", "answer": "Sebaliknya" },
{ "question": "Our", "answer": "Kami" },
{ "question": "Out", "answer": "Diluar" },
{ "question": "Coverage", "answer": "Liputan / cakupan" },
    ],
  Part7NGSL: [
   { "question": "Outside", "answer": "Di luar" },
{ "question": "Party", "answer": "Pesta" },
{ "question": "Pass", "answer": "Lulus / melewati" },
{ "question": "Past", "answer": "Lampau" },
{ "question": "Patient", "answer": "Sabar" },
{ "question": "Pattern", "answer": "Pola" },
{ "question": "Pay", "answer": "Membayar" },
{ "question": "Peace", "answer": "Perdamaian" },
{ "question": "People", "answer": "Orang - orang" },
{ "question": "Pocket", "answer": "Saku" },
{ "question": "Perform", "answer": "Melakukan" },
{ "question": "Performance", "answer": "Kinerja" },
{ "question": "Perhaps", "answer": "Mungkin" },
{ "question": "Period", "answer": "Titik" },
{ "question": "Over", "answer": "Lebih" },
{ "question": "Own", "answer": "Sendiri" },
{ "question": "Owner", "answer": "Pemilik" },
{ "question": "Page", "answer": "Halaman" },
{ "question": "Pain", "answer": "Rasa sakit" },
{ "question": "Painting", "answer": "Lukisan" },
{ "question": "Paper", "answer": "Kertas" },
{ "question": "Parent", "answer": "Orang tua" },
{ "question": "Part", "answer": "Bagian" },
{ "question": "Participant", "answer": "Peserta" },
{ "question": "Particular", "answer": "Tertentu" },
{ "question": "Particularly", "answer": "Terutama" },
{ "question": "Partner", "answer": "Pasangan" },
{ "question": "Person", "answer": "Orang" },
{ "question": "Personal", "answer": "Pribadi" },
{ "question": "Phone", "answer": "Telepon" },
{ "question": "Physical", "answer": "Fisik" },
{ "question": "Pick", "answer": "Memilih" },
{ "question": "Picture", "answer": "Gambar" },
{ "question": "Piece", "answer": "Bagian" },
{ "question": "Place", "answer": "Tempat" },
{ "question": "Play", "answer": "Bermain" },
{ "question": "Plan", "answer": "Rencana" },
{ "question": "Plant", "answer": "Menanam" },
{ "question": "Prevent", "answer": "Mencegah" },
{ "question": "Price", "answer": "Harga" },
{ "question": "Private", "answer": "Pribadi" },
{ "question": "Probably", "answer": "Mungkin" },
{ "question": "Problem", "answer": "Masalah" },
{ "question": "Process", "answer": "Proses" },
{ "question": "Produce", "answer": "Menghasilkan" },
{ "question": "Product", "answer": "Produk" },
{ "question": "Production", "answer": "Produksi" },
{ "question": "Professional", "answer": "Profesional" },
{ "question": "Professor", "answer": "Profesor" },
{ "question": "Program", "answer": "Program" },
{ "question": "Project", "answer": "Proyek" },
{ "question": "Property", "answer": "Properti" },
{ "question": "Protect", "answer": "Melindungi" },
{ "question": "Prove", "answer": "Membuktikan" },
{ "question": "Player", "answer": "Pemain" },
{ "question": "Pay off", "answer": "Melunasi" },
{ "question": "Point", "answer": "Titik" },
{ "question": "Police", "answer": "Polisi" },
{ "question": "Policy", "answer": "Kebijakan" },
{ "question": "Point of view", "answer": "Sudut pandang / opini" },
{ "question": "Politics", "answer": "Politik" },
{ "question": "Poor", "answer": "Miskin" },
{ "question": "Popular", "answer": "Populer" },
{ "question": "Population", "answer": "Populasi" },
{ "question": "Position", "answer": "Posisi" },
{ "question": "Positive", "answer": "Positif" },
{ "question": "Possible", "answer": "Bisa jadi / mungkin" },
{ "question": "Power", "answer": "Kekuasaan" },
{ "question": "Practice", "answer": "Praktek" },
{ "question": "Prepare", "answer": "Mempersiapkan" },
{ "question": "Present", "answer": "Menyajikan" },
{ "question": "President", "answer": "Presiden" },
{ "question": "Pressure", "answer": "Tekanan" },
{ "question": "Pretty", "answer": "Cantik" },
{ "question": "Provide", "answer": "Menyediakan" },
{ "question": "Public", "answer": "Publik" },
{ "question": "Pull", "answer": "Tarik" },
{ "question": "Purpose", "answer": "Tujuan" },
{ "question": "Push", "answer": "Dorong" },
{ "question": "Republican", "answer": "Republik" },
{ "question": "Pray", "answer": "Berdoa" },
{ "question": "Require", "answer": "Memerlukan" },
{ "question": "Research", "answer": "Penelitian" },
{ "question": "Resource", "answer": "Sumber" },
{ "question": "Respond", "answer": "Menanggapi" },
{ "question": "Response", "answer": "Tanggapan" },
{ "question": "Responsibility", "answer": "Tanggung jawab" },
{ "question": "Rest", "answer": "Beristirahat" },
{ "question": "Result", "answer": "Hasil" },
{ "question": "Return", "answer": "Kembali" },
{ "question": "Reveal", "answer": "Mengungkapkan" },
{ "question": "Rich", "answer": "Kaya" },
{ "question": "Right", "answer": "Baik" },
{ "question": "Rise", "answer": "Bangkit" },
{ "question": "Risk", "answer": "Risiko" },
{ "question": "Rock", "answer": "Batu" },
{ "question": "Role", "answer": "Wewenang" },
{ "question": "Room", "answer": "Kamar" },
{ "question": "Rule", "answer": "Aturan" },
{ "question": "Run", "answer": "Lari" },
    ],
  Part8NGSL: [
   { "question": "Safe", "answer": "Aman" },
{ "question": "Same", "answer": "Sama" },
{ "question": "Save", "answer": "Menyimpan" },
{ "question": "Say", "answer": "Mengatakan" },
{ "question": "Scene", "answer": "Tempat kejadian" },
{ "question": "School", "answer": "Sekolah" },
{ "question": "Science", "answer": "Ilmu" },
{ "question": "Scientist", "answer": "Ilmuwan" },
{ "question": "Score", "answer": "Skor" },
{ "question": "Sea", "answer": "Laut" },
{ "question": "Religious", "answer": "Keagamaan" },
{ "question": "Remain", "answer": "Tetap" },
{ "question": "Remember", "answer": "Ingat" },
{ "question": "Remove", "answer": "Menghapus" },
{ "question": "Report", "answer": "Melaporkan" },
{ "question": "Represent", "answer": "Mewakili" },
{ "question": "Road", "answer": "Jalan" },
{ "question": "Season", "answer": "Musim" },
{ "question": "Seat", "answer": "Kursi" },
{ "question": "Second", "answer": "Kedua" },
{ "question": "Section", "answer": "Bagian" },
{ "question": "Security", "answer": "Keamanan" },
{ "question": "See", "answer": "Lihat" },
{ "question": "Seek", "answer": "Mencari" },
{ "question": "Seem", "answer": "Terlihat" },
{ "question": "Sell", "answer": "Menjual" },
{ "question": "Send", "answer": "Kirim" },
{ "question": "Seven", "answer": "Tujuh" },
{ "question": "Several", "answer": "Beberapa" },
{ "question": "Sex", "answer": "Seks" },
{ "question": "Sexual", "answer": "Seksual" },
{ "question": "Shake", "answer": "Menggoyang" },
{ "question": "Share", "answer": "Bagikan" },
{ "question": "She", "answer": "Dia" },
{ "question": "Shoot", "answer": "Menembak" },
{ "question": "Short", "answer": "Pendek" },
{ "question": "Senior", "answer": "Senior" },
{ "question": "Sense", "answer": "Merasakan" },
{ "question": "Series", "answer": "Seri" },
{ "question": "Serious", "answer": "Serius" },
{ "question": "Serve", "answer": "Menyajikan" },
{ "question": "Service", "answer": "Layanan" },
{ "question": "Set", "answer": "Set" },
{ "question": "Shot", "answer": "Tembakan" },
{ "question": "Should", "answer": "Sebaiknya" },
{ "question": "Shoulder", "answer": "Bahu" },
{ "question": "Show", "answer": "Menunjukan" },
{ "question": "Side", "answer": "Sisi" },
{ "question": "Significant", "answer": "Penting" },
{ "question": "Someoone", "answer": "Seseorang" },
{ "question": "Something", "answer": "Sesuatu" },
{ "question": "Sometimes", "answer": "Terkadang" },
{ "question": "Son", "answer": "Putra" },
{ "question": "Song", "answer": "Lagu" },
{ "question": "Soon", "answer": "Segera" },
{ "question": "Sort", "answer": "Menyortir" },
{ "question": "Sound", "answer": "Suara" },
{ "question": "Source", "answer": "Sumber" },
{ "question": "South", "answer": "Selatan" },
{ "question": "So much", "answer": "Sangat banyak" },
{ "question": "Space", "answer": "Ruang" },
{ "question": "Speak", "answer": "Berbicara" },
{ "question": "Special", "answer": "Khusus" },
{ "question": "Specific", "answer": "Spesifik" },
{ "question": "Speech", "answer": "Pidato" },
{ "question": "Spend", "answer": "Menghabiskan" },
{ "question": "Six", "answer": "Enam" },
{ "question": "Size", "answer": "Ukuran" },
{ "question": "Skill", "answer": "Keterampilan / keahlian" },
{ "question": "Skin", "answer": "Kulit" },
{ "question": "Small", "answer": "Kecil" },
{ "question": "Smile", "answer": "Tersenyum" },
{ "question": "So", "answer": "Begitu" },
{ "question": "Social", "answer": "Sosial" },
{ "question": "Society", "answer": "Masyarakat" },
{ "question": "Soldier", "answer": "Tentara" },
{ "question": "Some", "answer": "Beberapa" },
{ "question": "Somebody", "answer": "Seseorang" },
{ "question": "Similar", "answer": "Serupa" },
{ "question": "Simple", "answer": "Sederhana" },
{ "question": "Simply", "answer": "Secara sederhana" },
{ "question": "Since", "answer": "Sejak" },
{ "question": "Sing", "answer": "Bernyanyi" },
{ "question": "Single", "answer": "Tunggal" },
{ "question": "Sister", "answer": "Saudara" },
{ "question": "Sit", "answer": "Duduk" },
{ "question": "Site", "answer": "Situs" },
{ "question": "Situation", "answer": "Situasi" },
{ "question": "Put", "answer": "Taruh" },
{ "question": "Quality", "answer": "Kualitas" },
{ "question": "Question", "answer": "Pertanyaan" },
{ "question": "Quickly", "answer": "Segera" },
{ "question": "Quite", "answer": "Cukup" },
{ "question": "Race", "answer": "Ras" },
{ "question": "Radio", "answer": "Radio" },
{ "question": "Raise", "answer": "Menaikan" },
{ "question": "Range", "answer": "Jarak" },
{ "question": "Rate", "answer": "Menilai" },
{ "question": "Rather", "answer": "Agak" },
{ "question": "Reach", "answer": "Mencapai" },
    ],
  Part9NGSL: [
   { "question": "Read", "answer": "Baca" },
{ "question": "Ready", "answer": "Siap" },
{ "question": "Real", "answer": "Nyata" },
{ "question": "Recognize", "answer": "Mengakui" },
{ "question": "Record", "answer": "Merekam" },
{ "question": "Red", "answer": "Merah" },
{ "question": "Reduce", "answer": "Mengurangi" },
{ "question": "Reflect", "answer": "Mencerminkan" },
{ "question": "Region", "answer": "Wilayah" },
{ "question": "Relate", "answer": "Berhubungan" },
{ "question": "Relationship", "answer": "Hubungan" },
{ "question": "Reality", "answer": "Realitas" },
{ "question": "Realize", "answer": "Menyadari" },
{ "question": "Really", "answer": "Betulkah" },
{ "question": "Reason", "answer": "Alasan" },
{ "question": "Receive", "answer": "Menerima" },
{ "question": "Recent", "answer": "Baru" },
{ "question": "Recently", "answer": "Baru saja" },
{ "question": "Sport", "answer": "Olahraga" },
{ "question": "Spring", "answer": "Musim semi" },
{ "question": "Staff", "answer": "Staf" },
{ "question": "Stage", "answer": "Tahap" },
{ "question": "Stand", "answer": "Berdiri" },
{ "question": "Standard", "answer": "Standar" },
{ "question": "Star", "answer": "Bintang" },
{ "question": "Start", "answer": "Mulailah" },
{ "question": "State", "answer": "Negara" },
{ "question": "Statement", "answer": "Pernyataan" },
{ "question": "Station", "answer": "Stasiun" },
{ "question": "Stay", "answer": "Tinggal" },
{ "question": "Step", "answer": "Langkah" },
{ "question": "Still", "answer": "Masih" },
{ "question": "Sure", "answer": "Tentu" },
{ "question": "Surface", "answer": "Permukaan" },
{ "question": "System", "answer": "Sistem" },
{ "question": "Table", "answer": "Meja" },
{ "question": "Take", "answer": "Mengambil" },
{ "question": "Talk", "answer": "Berbicara" },
{ "question": "Task", "answer": "Tugas" },
{ "question": "Tax", "answer": "Pajak" },
{ "question": "Such", "answer": "Seperti itu" },
{ "question": "Suddenly", "answer": "Mendadak" },
{ "question": "Suffer", "answer": "Menderita" },
{ "question": "Suggest", "answer": "Menyarankan" },
{ "question": "Summer", "answer": "Musim panas" },
{ "question": "Support", "answer": "Dukung" },
{ "question": "Teach", "answer": "Mengajar" },
{ "question": "Teacher", "answer": "Guru" },
{ "question": "Team", "answer": "Tim" },
{ "question": "Technology", "answer": "Teknologi" },
{ "question": "Television", "answer": "Televisi" },
{ "question": "Stock", "answer": "Persediaan" },
{ "question": "Stop", "answer": "Berhenti" },
{ "question": "Store", "answer": "Toko" },
{ "question": "Story", "answer": "Cerita" },
{ "question": "Strategy", "answer": "Strategi" },
{ "question": "Street", "answer": "Jalan" },
{ "question": "Strong", "answer": "Kuat" },
{ "question": "Structure", "answer": "Struktur" },
{ "question": "Student", "answer": "Siswa" },
{ "question": "Study", "answer": "Belajar" },
{ "question": "Stuff", "answer": "Barang" },
{ "question": "Style", "answer": "Gaya" },
{ "question": "Subject", "answer": "Subyek" },
{ "question": "Success", "answer": "Keberhasilan" },
{ "question": "Successful", "answer": "Sukses" },
{ "question": "Tell", "answer": "Menceritakan" },
{ "question": "The", "answer": "Itu" },
{ "question": "Their", "answer": "Mereka" },
{ "question": "Them", "answer": "Mereka" },
{ "question": "Themselves", "answer": "Diri mereka sendiri" },
{ "question": "Then", "answer": "Kemudian" },
{ "question": "Theory", "answer": "Teori" },
{ "question": "There", "answer": "Sana" },
{ "question": "These", "answer": "ini" },
{ "question": "They", "answer": "Mereka" },
{ "question": "Ten", "answer": "Sepuluh" },
{ "question": "Tend", "answer": "Cenderung" },
{ "question": "Term", "answer": "Istilah" },
{ "question": "Test", "answer": "Uji" },
{ "question": "Than", "answer": "Dari" },
{ "question": "Thank", "answer": "Terimakasih" },
{ "question": "That", "answer": "Bahwa" },
{ "question": "Thing", "answer": "Benda" },
{ "question": "Think", "answer": "Berpikir" },
{ "question": "Third", "answer": "Ketiga" },
{ "question": "This", "answer": "Ini" },
{ "question": "Those", "answer": "Itu" },
{ "question": "Though", "answer": "Meskipun" },
{ "question": "Thought", "answer": "Pikir / pemikiran / pendapat" },
{ "question": "Thousand", "answer": "Ribu" },
{ "question": "Threat", "answer": "Ancaman" },
{ "question": "Three", "answer": "Tiga" },
{ "question": "Through", "answer": "Melalui" },
{ "question": "Trial", "answer": "Percobaan" },
{ "question": "Trip", "answer": "Perjalanan" },
{ "question": "Trouble", "answer": "Masalah" },
{ "question": "True", "answer": "Benar" },
{ "question": "Truth", "answer": "Kebenaran" },
{ "question": "Try", "answer": "Mencoba" },
    ],
  Part10NGSL: [
   { "question": "Turn", "answer": "Belok" },
{ "question": "TV", "answer": "Televisi" },
{ "question": "Two", "answer": "Dua" },
{ "question": "Type", "answer": "Tipe" },
{ "question": "Under", "answer": "Dibawah" },
{ "question": "Understand", "answer": "Memahami" },
{ "question": "Throughout", "answer": "Sepanjang" },
{ "question": "Throw", "answer": "Melemparkan" },
{ "question": "Trust", "answer": "Memercayai" },
{ "question": "Time", "answer": "Waktu" },
{ "question": "To", "answer": "Untuk" },
{ "question": "Today", "answer": "Hari ini" },
{ "question": "Together", "answer": "Bersama" },
{ "question": "Tonight", "answer": "Malam ini" },
{ "question": "Too", "answer": "Terlalu" },
{ "question": "Top", "answer": "Puncak" },
{ "question": "Total", "answer": "Total" },
{ "question": "Tough", "answer": "Sulit" },
{ "question": "Toward", "answer": "Terhadap" },
{ "question": "Town", "answer": "Kota" },
{ "question": "Trade", "answer": "Perdagangan" },
{ "question": "Traditional", "answer": "Tradisional" },
{ "question": "Training", "answer": "Latihan" },
{ "question": "Various", "answer": "Berbagai" },
{ "question": "Very", "answer": "Sangat" },
{ "question": "Victim", "answer": "Korban" },
{ "question": "View", "answer": "Melihat" },
{ "question": "Violence", "answer": "Kekerasan" },
{ "question": "Visit", "answer": "Mengunjungi" },
{ "question": "Voice", "answer": "Suara" },
{ "question": "Vote", "answer": "Pilih" },
{ "question": "Wait", "answer": "Tunggu" },
{ "question": "Walk", "answer": "Berjalan" },
{ "question": "Travel", "answer": "Perjalanan" },
{ "question": "Treat", "answer": "Memperlakukan" },
{ "question": "Treatment", "answer": "Pengobatan" },
{ "question": "Tree", "answer": "Pohon" },
{ "question": "Unit", "answer": "Satuan" },
{ "question": "Until", "answer": "Sampai" },
{ "question": "Up", "answer": "Naik" },
{ "question": "Upon", "answer": "Atas" },
{ "question": "Us", "answer": "Kami" },
{ "question": "Use", "answer": "Menggunakan" },
{ "question": "Usually", "answer": "Biasanya" },
{ "question": "Value", "answer": "Nilai" },
{ "question": "Wall", "answer": "Dinding" },
{ "question": "Want", "answer": "Ingin" },
{ "question": "War", "answer": "Perang" },
{ "question": "Where", "answer": "Dimana" },
{ "question": "Weather", "answer": "Cuaca" },
{ "question": "Which", "answer": "Yang" },
{ "question": "While", "answer": "Sementara" },
{ "question": "White", "answer": "Putih" },
{ "question": "Who", "answer": "Siapa" },
{ "question": "Whole", "answer": "Seluruh" },
{ "question": "Whom", "answer": "Siapa" },
{ "question": "Whose", "answer": "Punya siapa" },
{ "question": "Why", "answer": "Mengapa" },
{ "question": "Wide", "answer": "Lebar" },
{ "question": "Week", "answer": "Minggu" },
{ "question": "Weight", "answer": "Bobot" },
{ "question": "Well", "answer": "Baik" },
{ "question": "West", "answer": "Barat" },
{ "question": "Weak", "answer": "Lemah" },
{ "question": "What", "answer": "Apa" },
{ "question": "Whatever", "answer": "Masa bodo" },
{ "question": "When", "answer": "Kapan" },
{ "question": "Wife", "answer": "Istri" },
{ "question": "Will", "answer": "Akan" },
{ "question": "Win", "answer": "Menang" },
{ "question": "Wind", "answer": "Angin" },
{ "question": "Window", "answer": "Jendela" },
{ "question": "Wish", "answer": "Ingin" },
{ "question": "With", "answer": "Dengan" },
{ "question": "Within", "answer": "Dalam" },
{ "question": "Watch", "answer": "Menonton" },
{ "question": "Water", "answer": "Air" },
{ "question": "Way", "answer": "Cara / jalan" },
{ "question": "We", "answer": "Kita" },
{ "question": "Weapon", "answer": "Senjata" },
{ "question": "Wear", "answer": "Memakai" },
{ "question": "Without", "answer": "Tanpa" },
{ "question": "Woman", "answer": "Wanita" },
{ "question": "Wonder", "answer": "Bertanya - tanya" },
{ "question": "Write", "answer": "Menulis" },
{ "question": "Writer", "answer": "Penulis" },
{ "question": "Wrong", "answer": "Salah" },
{ "question": "Yard", "answer": "Halaman" },
{ "question": "Yeah", "answer": "Ya" },
{ "question": "Year", "answer": "Tahun" },
{ "question": "Word", "answer": "Kata" },
{ "question": "Work", "answer": "Kerja" },
{ "question": "Worker", "answer": "Pekerja" },
{ "question": "World", "answer": "Dunia" },
{ "question": "Worry", "answer": "Khawatir" },
{ "question": "Would", "answer": "Akan" },
{ "question": "Yes", "answer": "Iya" },
{ "question": "Yet", "answer": "Namun / belum" },
{ "question": "You", "answer": "Kamu" },
{ "question": "Young", "answer": "Muda" },
{ "question": "Your", "answer": "Punya kamu" },
    ],

  
};